#!/usr/bin/env bun
/**
 * @module generate-health-dashboard
 * @description Generates the Repository Health Dashboard base on Code Inventory.
 */

import { existsSync } from 'node:fs';
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

async function main() {
  const inventoryPath = join(process.cwd(), 'docs/architecture/code_inventory.md');
  const dashboardPath = join(process.cwd(), 'docs/architecture/repository_health.md');

  if (!existsSync(inventoryPath)) {
    console.error('Inventory not found. Run maintain-inventory.ts first.');
    process.exit(1);
  }

  const content = await readFile(inventoryPath, 'utf-8');
  let totalFiles = 0;
  let auditedFiles = 0;

  const lines = content.split('\n');
  const categories = new Map<string, { total: number; audited: number }>();
  let currentCategory = 'Unknown';

  for (const line of lines) {
    if (line.trim().startsWith('### ')) {
      currentCategory = line.replace('### ', '').trim();
      if (!categories.has(currentCategory)) {
        categories.set(currentCategory, { total: 0, audited: 0 });
      }
    } else if (line.trim().startsWith('|') && !line.includes('---') && !line.includes('Filepath')) {
      const isAudited = line.includes('[x]');
      totalFiles++;
      let catStats = categories.get(currentCategory);
      if (!catStats) {
        catStats = { total: 0, audited: 0 };
        categories.set(currentCategory, catStats);
      }
      catStats.total++;
      if (isAudited) {
        auditedFiles++;
        catStats.audited++;
      }
    }
  }

  const overallCoverage = totalFiles > 0 ? ((auditedFiles / totalFiles) * 100).toFixed(2) : 0;

  let dashboard = `# 🏥 Repository Health Dashboard\n\n`;
  dashboard += `> Auto-generated by \`scripts/generate-health-dashboard.ts\`\n`;
  dashboard += `> Last updated: ${new Date().toISOString()}\n\n`;

  dashboard += `## Overview\n\n`;
  dashboard += `- **Total Tracked Files:** ${totalFiles}\n`;
  dashboard += `- **Audited/Reviewed:** ${auditedFiles}\n`;
  dashboard += `- **Overall Audit Coverage:** ${overallCoverage}%\n\n`;

  dashboard += `## Category Breakdown\n\n`;
  dashboard += `| Category | Total Files | Audited | Coverage |\n`;
  dashboard += `| :--- | :---: | :---: | :---: |\n`;

  for (const [category, stats] of categories.entries()) {
    const coverage = stats.total > 0 ? ((stats.audited / stats.total) * 100).toFixed(2) : 0;
    dashboard += `| ${category} | ${stats.total} | ${stats.audited} | ${coverage}% |\n`;
  }

  dashboard += `\n## Action Items\n`;
  dashboard += `> Review items with [ ] in the \`code_inventory.md\` to improve score.\n`;

  await writeFile(dashboardPath, dashboard, 'utf-8');
  console.log(`✅ Health Dashboard written to ${dashboardPath}`);
}

main().catch(console.error);
